import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { BookOpen, ExternalLink, FileText, Link2, Plus, Trash2 } from 'lucide-react';
import { EmptyClass } from '../components/EmptyClass';
import { PageHeader } from '../components/PageHeader';
import { useAuth } from '../context/AuthContext';
import { useClassRoom } from '../context/ClassContext';
import { cancelLibraryItem, listLibraryItems, saveLibraryItem } from '../services/libraryService';
import type { LibraryItem } from '../types';

export function LibraryPage() {
  const { currentClassId } = useClassRoom(); const { profile, can } = useAuth();
  const canEdit = profile?.role === 'admin' || profile?.role === 'teacher' || profile?.role === 'assistant' || can('manageClassContent');
  const [items, setItems] = useState<LibraryItem[]>([]); const [showForm, setShowForm] = useState(false); const [search, setSearch] = useState(''); const [title, setTitle] = useState(''); const [category, setCategory] = useState('Tài liệu học tập'); const [description, setDescription] = useState(''); const [url, setUrl] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function reload() { if (currentClassId) setItems(await listLibraryItems(currentClassId)); }
  useEffect(() => { void reload(); }, [currentClassId]);
  const filtered = useMemo(() => items.filter((item) => `${item.title} ${item.category} ${item.description || ''}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  async function submit(e: FormEvent) { e.preventDefault(); if (!currentClassId || !profile || !title || !url) return; setBusy(true); setError(''); try { await saveLibraryItem({ classId: currentClassId, title, category, description, url, owner: profile.displayName, creatorUid: profile.uid, creatorName: profile.displayName }); setTitle(''); setDescription(''); setUrl(''); setShowForm(false); await reload(); } catch (err) { setError(err instanceof Error ? err.message : 'Không thể lưu tài liệu.'); } finally { setBusy(false); } }
  if (!currentClassId) return <EmptyClass />;
  return <><PageHeader title="Thư viện lớp" description="Kho liên kết tài liệu học tập, biểu mẫu, video, tài nguyên lớp và tài liệu phụ huynh." actions={canEdit ? <button className="btn primary" onClick={() => setShowForm((v) => !v)}><Plus size={16} />Thêm tài liệu</button> : undefined} />{error && <div className="alert danger">{error}</div>}
  {showForm && canEdit && <form className="card form-card" onSubmit={submit}><div className="form-grid cols-3"><label>Tên tài liệu<input required value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Nhóm<select value={category} onChange={(e) => setCategory(e.target.value)}><option>Tài liệu học tập</option><option>Biểu mẫu</option><option>Video</option><option>Hoạt động</option><option>Phụ huynh</option><option>Khác</option></select></label><label>Liên kết<input required value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://..." /></label><label className="span-2">Mô tả<textarea value={description} onChange={(e) => setDescription(e.target.value)} /></label></div><div className="row-actions end"><button type="button" className="btn ghost" onClick={() => setShowForm(false)}>Hủy</button><button className="btn primary" disabled={busy}>Lưu tài liệu</button></div></form>}
  <div className="library-toolbar"><div className="search-with-icon"><BookOpen size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm tài liệu..." /></div><span>{filtered.length} tài liệu</span></div><div className="library-grid">{filtered.map((item) => <article className="library-card" key={item.id}><div className="library-icon">{item.category === 'Video' ? '🎬' : item.category === 'Biểu mẫu' ? '📋' : item.category === 'Phụ huynh' ? '👨‍👩‍👧' : '📚'}</div><div><span className="pill teal">{item.category}</span><h3>{item.title}</h3><p>{item.description || 'Tài liệu dùng chung của lớp.'}</p><small><Link2 size={12} /> {item.owner || item.creatorName}</small></div><div className="library-actions"><a className="btn ghost" href={item.url} target="_blank" rel="noreferrer"><ExternalLink size={14} />Mở</a>{canEdit && <button className="plain-icon danger-text" onClick={async () => { if (!confirm(`Ẩn tài liệu “${item.title}”?`)) return; await cancelLibraryItem(currentClassId, item.id); await reload(); }}><Trash2 size={14} /></button>}</div></article>)}{filtered.length === 0 && <div className="empty-inline span-all"><FileText size={24} /> Chưa có tài liệu phù hợp.</div>}</div></>;
}
